export enum Category {
  Beef = "Beef",
  Chicken = "Chicken",
  Dessert = "Dessert",
  Lamb = "Lamb",
  Miscellaneous = "Miscellaneous",
  Pasta = "Pasta",
  Pork = "Pork",
  Seafood = "Seafood",
  Side = "Side",
  Soup = "Soup",
  Starter = "Starter",
  Vegan = "Vegan",
  Vegetarian = "Vegetarian",
}

export enum Area {
  American = "American",
  British = "British",
  Canadian = "Canadian",
  Chinese = "Chinese",
  Egyptian = "Egyptian",
  French = "French",
  Greek = "Greek",
  Indian = "Indian",
  Irish = "Irish",
  Italian = "Italian",
  Jamaican = "Jamaican",
  Japanese = "Japanese",
  Kenyan = "Kenyan",
  Malaysian = "Malaysian",
  Mexican = "Mexican",
  Moroccan = "Moroccan",
  Portuguese = "Portuguese",
  Russian = "Russian",
  Spanish = "Spanish",
  Thai = "Thai",
  Tunisian = "Tunisian",
  Turkish = "Turkish",
  Unknown = "Unknown",
}
